#!/bin/bash
#apply_wal_scheme
#applies the colorscheme to the major WM elements (i3 & polybar)
#actualizes the lightdm background in consequence

wallpaper=$(cat ~/.cache/wal/wal)
cp $wallpaper /home/kaegell/Pictures/Misc/lightdm.jpg
i3-msg reload
pres=$(pgrep polybar)
if [[ -z $pres ]]; then
	polybar -r topbar& > /dev/null 2>&1
else
	echo "" >> ~/.config/polybar/config
fi
